### ISSUE TITLE
TimeSinceEpoch is not correct

### ISSUE THREAD

**Issue by rickywei** [chromedp/cdproto-gen#22] opened 2023-05-30 13:33 UTC
It seems that the time should multiply time.Millisecond (1e6) rather than time.Second (1e9)

The corresponding code in cdproto are [https://github.com/chromedp/cdproto/blob/8501c74e8228308e0dbd4aedb1f24ea1c103dd6e/network/types.go#LL1027](https://github.com/chromedp/cdproto/blob/8501c74e8228308e0dbd4aedb1f24ea1c103dd6e/network/types.go#LL1027)
and
[https://github.com/chromedp/cdproto/blob/8501c74e8228308e0dbd4aedb1f24ea1c103dd6e/cdp/types.go#L742](https://github.com/chromedp/cdproto/blob/8501c74e8228308e0dbd4aedb1f24ea1c103dd6e/cdp/types.go#L742)

The following code snapshot is what I tried

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	// a response time from cdp log
	t := 1.685446691349539e+12

	// correct time 2023-05-30 19:38:11.349539072 +0800 CST
	fmt.Println(time.Unix(0, int64(t*float64(time.Millisecond))))

	// wrong time 1677-09-21 08:12:43.145224192 +0800 CST
	fmt.Println(time.Unix(0, int64(t*float64(time.Second))))
}
```

**Comment by kenshaw** [comment] 2023-05-30 20:25
@RickyWei Thanks for bringing this to my attention. I'll look at this. I don't recall specifically why I implemented this as I did at the time, except to mention that the behavior has at time been incorrect on Chromium's code base, and documented incorrectly.

In the interim, I'd suggest just multiplying the time value if you need the different value at the moment.

**Comment by kenshaw** [comment] 2023-06-01 22:40
@RickyWei I've changed this, but I'm not yet going to update this on the `chromedp` package. In the interim, you can update to the latest `cdproto` package. I will need to do some testing against the many other places `TimeSinceEpoch` is used to determine if this is sound/correct, or it's only with the `network.Response` type where this differs.

**Comment by ZekeLu** [comment] 2023-06-01 23:18
Good morning Ken!

I checked the `Network.requestWillBeSent` and `Network.responseReceived` events, only `response.responseTime` in `Network.responseReceived` contains the number of milliseconds (which is conflicted with the document).

- Network.requestWillBeSent
    - [x] wallTime
- Network.responseReceived
    - [ ] response.responseTime
    - [x] response.securityDetails.validFrom
    - [x] response.securityDetails.validTo

**Network.requestWillBeSent** (truncated)

```json
{
  "requestId": "4393E3633F10D1113C22E7A368A550C4",
  "loaderId": "4393E3633F10D1113C22E7A368A550C4",
  "documentURL": "https://bing.com/",
  "request": {
    "url": "https://bing.com/",
    "method": "GET"
  },
  "timestamp": 13720.870149,
  "wallTime": 1685659975.297646
}
```

**Network.responseReceived** (truncated):

```json
{
  "type": "Document",
  "response": {
    "url": "https://cn.bing.com/",
    "status": 200,
    "statusText": "",
    "responseTime": 1685659975757.947,
    "securityDetails": {
      "protocol": "TLS 1.2",
      "keyExchange": "ECDHE_RSA",
      "keyExchangeGroup": "P-384",
      "cipher": "AES_256_GCM",
      "certificateId": 0,
      "subjectName": "www.bing.com",
      "issuer": "Microsoft RSA TLS CA 02",
      "validFrom": 1676519265,
      "validTo": 1692157665
    }
  }
}
```

**Comment by kenshaw** [comment] 2023-06-01 23:31
@ZekeLu much appreciated. I haven't had time to go through all the places where there are timestamps in the `cdproto` code to check everything. Obviously before tagging anything, this should be done, and confirmed. My greatest concern is with the `input.*` events, as those are likely being used by actual complex programs.

**Comment by ZekeLu** [comment] 2023-06-01 23:34
I will try to go through all of them today.

**Comment by kenshaw** [comment] 2023-06-01 23:38
@ZekeLu you're amazing man. I appreciate the help!

**Comment by rickywei** [comment] 2023-06-03 04:43
@ZekeLu @kenshaw Thanks for all of your effort. I really appreciate it. 👍👍

**Comment by ZekeLu** [comment] 2023-06-03 08:56
Below is the full list of the places where `Network.TimeSinceEpoch` or `Input.TimeSinceEpoch` are used. Among them, only `Response.responseTime` does not carry the correct value (in respect of the CDP doc).

Please note that I'm not familiar with Chromium, and the listed Chromium Implementation could be wrong. But I think it's enough for finding out whether the implementation is consistent with the CDP doc.

### Network.TimeSinceEpoch

- CDP doc: [Network.TimeSinceEpoch](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-TimeSinceEpoch)
- cdproto package: [cdp.TimeSinceEpoch](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/cdp/types.go#L720)

| Seq | CDP doc | Chromium Implementation | cdproto package | Chromium |
| --- | ------- | ----------------------- | --------------- | -------- |
| 1 | Network<br>[Response](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-Response)<br>**responseTime** | `response.ResponseTime().ToJsTimeIgnoringNull()` | network<br>[Response](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/network/types.go#L1028)<br>**ResponseTime** | [BuildObjectForResourceResponse](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_network_agent.cc#L1037-L1040) |
| 2 | Network<br>[SecurityDetails](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-SecurityDetails)<br>**validFrom**<br>**validTo** | `ssl_info.cert->valid_start().ToDoubleT()`<br>`ssl_info.cert->valid_expiry().ToDoubleT()` | network<br>[SecurityDetails](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/network/types.go#L565-L566)<br>**ValidFrom**<br>**ValidTo** | [BuildSecurityDetails](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/network_handler.cc#L1803-L1804) |
| 3 | Network<br>[requestWillBeSent](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-requestWillBeSent)<br>**wallTime** | `base::Time::Now().ToDoubleT()` | network<br>[EventRequestWillBeSent](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/network/events.go#L70)<br>**WallTime** | InspectorNetworkAgent::<br>[WillSendRequestInternal](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_network_agent.cc#L1256-L1261) |
| 4 | Network<br>[webSocketWillSendHandshakeRequest](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-webSocketWillSendHandshakeRequest)<br>**wallTime** | `base::Time::Now().ToDoubleT()` | network<br>[EventWebSocketWillSendHandshakeRequest](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/network/events.go#L172)<br>**WallTime** | InspectorNetworkAgent::<br>[WillSendWebSocketHandshakeRequest](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_network_agent.cc#L1783-L1786) |
| 5 | Page<br>[OriginTrialToken](https://chromedevtools.github.io/devtools-protocol/tot/Page#type-OriginTrialToken)<br>**expiryTime** | `blink_trial_token.expiry_time().ToDoubleT()` | cdp<br>[OriginTrialToken](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/cdp/types.go#L1255)<br>**ExpiryTime** | [CreateOriginTrialToken](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_page_agent.cc#L1325) |
| 6 | Page<br>[FrameResource](https://chromedevtools.github.io/devtools-protocol/tot/Page#type-FrameResource)<br>**lastModified** | `last_modified.value().ToDoubleT()` | page<br>[FrameResource](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/page/types.go#L379)<br>**LastModified** | InspectorPageAgent::<br>[BuildObjectForResourceTree](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_page_agent.cc#L1504-L1505) |
| 7 | Page<br>[ScreencastFrameMetadata](https://chromedevtools.github.io/devtools-protocol/tot/Page#type-ScreencastFrameMetadata)<br>**timestamp** | `base::Time::Now().ToDoubleT()` | page<br>[ScreencastFrameMetadata](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/page/types.go#L512)<br>**Timestamp** | [BuildScreencastFrameMetadata](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/page_handler.cc#L153-L161) |
| 8 | Security<br>[CertificateSecurityState](https://chromedevtools.github.io/devtools-protocol/tot/Security#type-CertificateSecurityState)<br>**validFrom**<br>**validTo** | `state.certificate->valid_start().ToDoubleT()`<br>`state.certificate->valid_expiry().ToDoubleT()` | security<br>[CertificateSecurityState](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/security/types.go#L143-L144)<br>**ValidFrom**<br>**ValidTo** | [CreateCertificateSecurityState](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/chrome/browser/devtools/protocol/security_handler.cc#L99-L104) |
| 9 | Storage<br>[interestGroupAccessed](https://chromedevtools.github.io/devtools-protocol/tot/Storage#event-interestGroupAccessed)<br>**accessTime** | `access_time.ToDoubleT()` | storage<br>[EventInterestGroupAccessed](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/storage/events.go#L55)<br>**AccessTime** | StorageHandler::<br>[OnInterestGroupAccessed](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/storage_handler.cc#L1020-L1021) |
| 10 | Storage<br>[sharedStorageAccessed](https://chromedevtools.github.io/devtools-protocol/tot/Storage#event-sharedStorageAccessed)<br>**accessTime** | `access_time.ToDoubleT()` | storage<br>[EventSharedStorageAccessed](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/storage/events.go#L66)<br>**AccessTime** | StorageHandler::<br>[NotifySharedStorageAccessed](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/storage_handler.cc#L1552-L1554) |
| 11 | Storage<br>[InterestGroupDetails](https://chromedevtools.github.io/devtools-protocol/tot/Storage#type-InterestGroupDetails)<br>**expirationTime** | `group.expiry.ToDoubleT()` | storage<br>[InterestGroupDetails](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/storage/types.go#L193)<br>**ExpirationTime** | [SendGetInterestGroup](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/storage_handler.cc#L1067-L1076) |
| 418 | Storage<br>[SharedStorageMetadata](https://chromedevtools.github.io/devtools-protocol/tot/Storage#type-SharedStorageMetadata)<br>**creationTime** | `metadata.creation_time.ToDoubleT()` | storage<br>[SharedStorageMetadata](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/storage/types.go#L305)<br>**CreationTime** | [SendSharedStorageMetadata](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/storage_handler.cc#L1187-L1192) |
| 420 | Storage<br>[StorageBucketInfo](https://chromedevtools.github.io/devtools-protocol/tot/Storage#type-StorageBucketInfo)<br>**expiration** | `bucket.expiration.ToDoubleT()` | storage<br>[BucketInfo](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/storage/types.go#L401)<br>**Expiration** | [BuildBucketInfo](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/storage_handler.cc#L150-L157) |
| 14 | BackgroundService<br>[BackgroundServiceEvent](https://chromedevtools.github.io/devtools-protocol/tot/BackgroundService#type-BackgroundServiceEvent)<br>**Timestamp** | `timestamp.ToJsTime() / 1'000` | backgroundservice<br>[Event](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/backgroundservice/types.go#L87)<br>**Timestamp** | [ToBackgroundServiceEvent](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/background_service_handler.cc#L82-L94) |
| 15 | Network<br>[ReportingApiReport](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-ReportingApiReport)<br>**timestamp** | `(report.queued - base::TimeTicks::UnixEpoch()).InSecondsF())` | network<br>[ReportingAPIReport](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/network/types.go#L1881)<br>**Timestamp** | NetworkHandler::<br>[BuildProtocolReport](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/network_handler.cc#L1337-L1338) |
| 16 | PerformanceTimeline<br>[LargestContentfulPaint](https://chromedevtools.github.io/devtools-protocol/tot/PerformanceTimeline#type-LargestContentfulPaint)<br>**renderTime**<br>**loadTime** | `ToProtocolTime(timeOrigin, lcp.renderTime())`<br>`ToProtocolTime(timeOrigin, lcp.loadTime())` | performancetimeline<br>[LargestContentfulPaint](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/performancetimeline/types.go#L15-L16)<br>**RenderTime**<br>**LoadTime** | [BuildEventDetails](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_performance_timeline_agent.cc#L40-L44) |
| 17 | PerformanceTimeline<br>[LayoutShift](https://chromedevtools.github.io/devtools-protocol/tot/PerformanceTimeline#type-LayoutShift)<br>**lastInputTime** | `ToProtocolTime(timeOrigin, ls.lastInputTime())` | performancetimeline<br>[LayoutShift](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/performancetimeline/types.go#L40)<br>**LastInputTime** | [BuildEventDetails](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_performance_timeline_agent.cc#L83-L89) |
| 18 | PerformanceTimeline<br>[TimelineEvent](https://chromedevtools.github.io/devtools-protocol/tot/PerformanceTimeline#type-TimelineEvent)<br>**time** | `ToProtocolTime(timeOrigin, entry->startTime())` | performancetimeline<br>[TimelineEvent](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/performancetimeline/types.go#L51)<br>**Time** | [BuildProtocolEvent](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_performance_timeline_agent.cc#L97-L104) |
| 19 | Emulation<br>[setVirtualTimePolicy](https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setVirtualTimePolicy)<br>**initialVirtualTime** | `base::Time::FromDoubleT(initial_virtual_time.fromJust())` | emulation<br>[SetVirtualTimePolicyParams](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/emulation/emulation.go#L614)<br>**InitialVirtualTime** | InspectorEmulationAgent::<br>[setVirtualTimePolicy](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_emulation_agent.cc#L464-L467) |
| 20 | Network<br>[setCookie](https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setCookie)<br>**expires** | `MakeCookieFromProtocolValues` | network<br>[SetCookieParams](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/network/network.go#L686)<br>**Expires** | NetworkHandler::<br>[SetCookie](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/network_handler.cc#L1544-L1548) |
| 21 | Network<br>[CookieParam](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-CookieParam)<br>**expires** | `MakeCookieFromProtocolValues` | network<br>[CookieParam](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/network/types.go#L1322)<br>**Expires** | NetworkHandler::<br>[SetCookies](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/network_handler.cc#L1592-L1597) |

[ToProtocolTime](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/third_party/blink/renderer/core/inspector/inspector_performance_timeline_agent.cc#L32C1-L35):

```cc
double ToProtocolTime(DOMHighResTimeStamp timeOrigin,
                      DOMHighResTimeStamp time) {
  return time ? ConvertDOMHighResTimeStampToSeconds(timeOrigin + time) : 0.0;
}
```

[MakeCookieFromProtocolValues](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/network_handler.cc#L381-L384):

```cc
  if (expires >= 0) {
    expiration_date =
        expires ? base::Time::FromDoubleT(expires) : base::Time::UnixEpoch();
  }
```

### Input.TimeSinceEpoch

- CDP doc: [Input.TimeSinceEpoch](https://chromedevtools.github.io/devtools-protocol/tot/Input#type-TimeSinceEpoch)
- cdproto package: [input.TimeSinceEpoch ](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/input/types.go#L140)

| Seq | CDP doc | Chromium Implementation | cdproto package | Chromium |
| --- | ------- | ----------------------- | --------------- | -------- |
| 1 | Input<br>[dispatchKeyEvent](https://chromedevtools.github.io/devtools-protocol/tot/Input#method-dispatchKeyEvent)<br>**timestamp** | `GetEventTimeTicks(timestamp)` | input<br>[DispatchKeyEventParams](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/input/input.go#L59)<br>**Timestamp** | InputHandler::<br>[DispatchKeyEvent](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/input_handler.cc#L801-L806) |
| 2 | Input<br>[dispatchMouseEvent](https://chromedevtools.github.io/devtools-protocol/tot/Input#method-dispatchMouseEvent)<br>**timestamp** | `GetEventTimeTicks(timestamp)` | input<br>[DispatchMouseEventParams](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/input/input.go#L269)<br>**Timestamp** | [CreateWebMouseEvent](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/input_handler.cc#L393) |
| 3 | Input<br>[dispatchTouchEvent](https://chromedevtools.github.io/devtools-protocol/tot/Input#method-dispatchTouchEvent)<br>**timestamp** | `GetEventTimeTicks(timestamp)` | input<br>[DispatchTouchEventParams](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/input/input.go#L398)<br>**Timestamp** | [CreateWebTouchEvents](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/input_handler.cc#L449) |
| 4 | Input<br>[emulateTouchFromMouseEvent](https://chromedevtools.github.io/devtools-protocol/tot/Input#method-emulateTouchFromMouseEvent)<br>**timestamp** | `GetEventTimeTicks(timestamp)` | input<br>[EmulateTouchFromMouseEventParams](https://github.com/chromedp/cdproto/blob/175ba2b55caf633748642c1ce299b4e4bdc2f63c/input/input.go#L441)<br>**Timestamp** | InputHandler::<br>[EmulateTouchFromMouseEvent](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/input_handler.cc#L1526-1548) |

[GetEventTimeTicks](https://github.com/chromium/chromium/blob/fb0b97175c0290aecba467189f770c328cdb6d54/content/browser/devtools/protocol/input_handler.cc#LL113C1-L119C2)

```cc
base::TimeTicks GetEventTimeTicks(const Maybe<double>& timestamp) {
  // Convert timestamp, in seconds since unix epoch, to an event timestamp
  // which is time ticks since platform start time.
  return timestamp.isJust() ? base::Seconds(timestamp.fromJust()) +
                                  base::TimeTicks::UnixEpoch()
                            : base::TimeTicks::Now();
}
```

**Comment by ZekeLu** [comment] 2023-06-03 09:58
We can add some code to correct `responseTime` for the `cdproto` users. But since this issue is not noticed for a long time, I think it's OK to leave it as what it is now and just wait for the upstream (Chromium) to fix it. BTW, I have just reported the issue to the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1451082.

**Comment by kenshaw** [comment] 2023-06-03 21:55
@ZekeLu in your opinion should we revert/change back the `Millisecond` resolution on `pdlgen`/`cdproto-gen`?

**Comment by kenshaw** [comment] 2023-06-03 21:58
@ZekeLu There are other possibilities as well: we can manually mark certain fields in the generator's `fixup` package, and add an additional field to the `TimeSinceEpoch` that tells the resolution. Alternately, I can write some code that tries to "guess" what the time is supposed to be, based on how large/small the value is.

**Comment by ZekeLu** [comment] 2023-06-04 03:20
Hi Ken. Yes I think we should revert the `Millisecond` resolution on `pdlgen` because the initial implementation is correct. And only `responseTime` in the `Response` type is wrong.

> Alternately, I can write some code that tries to "guess" what the time is supposed to be, based on how large/small the value is

This is what came up to my mind too.

I think it's better to limit the change to the `responseTime` field only. But I can not find a easy fix to `pdlgen` to do this.

**Comment by kenshaw** [comment] 2023-06-05 00:19
I just pushed a commit to `cdproto` that uses a different type just for the `responseTime` field (`cdp.TimeSinceEpochMilli`). It has the same interface as `cdp.TimeSinceEpoch`, but uses millisecond resolution. Should the Chromium code change, this will need to be change accordingly. 

@ZekeLu if you can check this out, assuming all the various time times are correct, we should tag a new version of `chromedp` with the updated `cdproto` dependency.

**Comment by ZekeLu** [comment] 2023-06-05 07:21
Thank you @kenshaw ! I have sent a PR to upgrade cdproto. And I have modified an existing test to check the `responseTime` so that we will be noticed once chromium fixed the issue.

If you're OK with the PR, I will tag a new release as `0.9.2`.

**Comment by ZekeLu** [comment] 2023-08-05 03:35
https://bugs.chromium.org/p/chromium/issues/detail?id=1451082 is closed as "WontFix". So it's good to go with `cdp.TimeSinceEpochMilli`. I'm going to tag a new release.

**Closed as completed** 2023-08-05 03:51 UTC
